# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Books For Babies
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Books for babies program, created by Dr. Sheila Knerr, a CHOP
  pediatric hospitalist.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.jmktest.net" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 2doggirl
github_username:  jeffknerr

# Build settings
#theme: minima
theme: bay_jekyll_theme
plugins:
  - jekyll-feed

header:
  pages:
    - name: Home
      slug: /     # <-- index.md
    - name: Blog  # <-- blog.md
    - name: About  # <-- blog.md
#   - name: Whatever  # <-- whatever.md

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: books4babies@b4b.com
      link: mailto:books4babies@b4b.com
  follow:
    - name: Twitter
      link: http://twitter.com/2doggirl
      username: "@2doggirl"
    - name: LinkedIn
      link: http://linkedin.com/in/YourLinkedInUsername

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
